# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dictation toolbox
email: mike@mikeroberts.xyz
description: > # this means to ignore newlines until "baseurl:"
  Up-to-date resources relating to every aspect of controlling a computer without using a keyboard and mouse.
# baseurl: "/pages" # the subpath of your site, e.g. /blog
url: "http://dictation-toolbox.org" # the base hostname & protocol for your site
# twitter_username: Taffyer
github_username:  dictation-toolbox
include: ['_pages']
collections:
  pages:
    output: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
